apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: go-strava
      context: ./
deploy:
  kubectl:
    manifests:
      - kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: go-strava
    port: 8080
    localPort: 9000